/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Apache Wayang (incubating)",
  "tagline": "Privacy-Preserving Federated Data Processing",
  "favicon": "img/wayang-logo.jpg",
  "url": "https://wayang.apache.org",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts"
        },
        "blog": {
          "blogSidebarCount": "ALL",
          "blogSidebarTitle": "All our posts",
          "showReadingTime": true
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    "/Users/alo/Development/wayang/incubator-wayang-website/node_modules/docusaurus-lunr-search/src/index.js"
  ],
  "themeConfig": {
    "navbar": {
      "title": "",
      "logo": {
        "alt": "Wayang Logo",
        "src": "img/wayang.png"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "startSidebar",
          "position": "right",
          "label": "Download"
        },
        {
          "type": "docSidebar",
          "sidebarId": "introductionSidebar",
          "position": "right",
          "label": "About"
        },
        {
          "type": "docSidebar",
          "sidebarId": "guideSidebar",
          "position": "right",
          "label": "Developers"
        },
        {
          "type": "dropdown",
          "label": "Community",
          "position": "right",
          "items": [
            {
              "label": "Blog",
              "to": "/blog/"
            },
            {
              "type": "docSidebar",
              "sidebarId": "communitySidebar",
              "label": "Project"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "ASF",
          "position": "right",
          "items": [
            {
              "label": "Foundation",
              "to": "https://www.apache.org/"
            },
            {
              "label": "License",
              "to": "https://www.apache.org/licenses/"
            },
            {
              "label": "Events",
              "to": "https://www.apache.org/events/current-event.html"
            },
            {
              "label": "Privacy",
              "to": "https://privacy.apache.org/policies/privacy-policy-public.html"
            },
            {
              "label": "Security",
              "to": "https://www.apache.org/security/"
            },
            {
              "label": "Sponsorship",
              "to": "https://www.apache.org/foundation/sponsorship.html"
            },
            {
              "label": "Thanks",
              "to": "https://www.apache.org/foundation/thanks.html"
            },
            {
              "label": "Code of Conduct",
              "to": "https://www.apache.org/foundation/policies/conduct.html"
            }
          ]
        },
        {
          "href": "https://github.com/apache/incubator-wayang",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Community",
          "items": [
            {
              "label": "Mailing list",
              "href": "https://lists.apache.org/list.html?dev@wayang.apache.org"
            },
            {
              "label": "Reddit",
              "href": "https://www.reddit.com/r/ApacheWayang"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/apachewayang"
            }
          ]
        },
        {
          "title": "Docs",
          "items": [
            {
              "label": "Install",
              "to": "/docs/start/download"
            },
            {
              "label": "Features",
              "to": "/docs/introduction/features"
            },
            {
              "label": "Benchmark",
              "to": "/docs/introduction/benchmark"
            }
          ]
        },
        {
          "title": "Repositories",
          "items": [
            {
              "label": "Wayang",
              "href": "https://github.com/apache/incubator-wayang"
            },
            {
              "label": "Website",
              "href": "https://github.com/apache/incubator-wayang-website"
            }
          ]
        }
      ],
      "logo": {
        "width": 200,
        "src": "/img/apache-incubator.svg",
        "href": "https://incubator.apache.org/",
        "alt": "Apache Incubator logo"
      },
      "copyright": "<div>\n      <p> Apache Wayang is an effort undergoing incubation at The Apache Software Foundation (ASF), sponsored by the Apache Incubator. Incubation is required of all newly accepted projects until a further review indicates that the infrastructure, communications, and decision making process have stabilized in a manner consistent with other successful ASF projects. While incubation status is not necessarily a reflection of the completeness or stability of the code, it does indicate that the project has yet to be fully endorsed by the ASF. </p>\n      <p>\n        Copyright © 2024 The Apache Software Foundation, Licensed under the Apache License, Version 2.0. <br/>\n        Apache, the names of Apache projects, and the feather logo are either registered trademarks or trademarks of the Apache Software Foundation in the United States and/or other countries.\n      </p>\n      </div>"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "java",
        "javascript",
        "rust",
        "cpp",
        "c",
        "bash",
        "scala",
        "python"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
